name: CI

on:
  pull_request:
  push:
    branches: ["dev"]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install --no-interaction

      - name: Run tests
        run: |
          poetry run pytest -q tests

#      - name: Run flake8 (match Makefile)
#        run: |
#          poetry run flake8 --ignore=E501,W291,W503,W605 --exclude=venv src
